# Generated by Django 2.2 on 2019-05-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
