# Generated by Django 2.2 on 2019-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Select Gender', max_length=6),
            preserve_default=False,
        ),
    ]
