# Generated by Django 2.2 on 2019-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffregistration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Male', max_length=6),
        ),
    ]
