# Generated by Django 2.2 on 2019-05-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Male', max_length=6)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
