# Generated by Django 2.2 on 2019-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailinfo',
            name='std_section',
        ),
        migrations.AddField(
            model_name='studentshiftinfo',
            name='std_section',
            field=models.CharField(default='X', max_length=50),
            preserve_default=False,
        ),
    ]
