# Generated by Django 2.2 on 2019-06-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190521_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='roll',
        ),
        migrations.AddField(
            model_name='studentdetailinfo',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentDetailInfo')),
            ],
        ),
    ]
