# Generated by Django 2.2 on 2019-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190625_2325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdetailinfo',
            unique_together={('roll', 'std_class')},
        ),
    ]
